import { FORM_TYPE_SELECT, FORM_TYPE_IMG, FORM_TYPE_TEXT,FORM_TYPE_DATE_YMD } from "@/constants";
export const ENTITY = {
	id: {
		name: "流水号",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: true,
		nTable: true,
		nAddOrEdit: true
	},
	accReceiveCode: {
		name: "应收账款编号",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: false,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	accReceiveAmt: {
		name: "应收账款金额",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	supCode: {
		name: "供应商简称",
		type: FORM_TYPE_TEXT,
		addEditType: FORM_TYPE_SELECT,
		searchType: FORM_TYPE_SELECT,
		rMapper:  true,		
		opt: null,
		searchWidth:"305px",
		inputWidth: "200px",
		nSearch: false,
		readSort: 0,
		searchAuth: true,
		nRead: true,
		nTable: true,
		gotListL:"supShortName",
		gotListV:"supCode"
	},
	supCodeName: {
		name: "供应商简称",
		type: FORM_TYPE_TEXT,
		addEditType: FORM_TYPE_SELECT,
		searchType: FORM_TYPE_SELECT,
		rMapper:  true,		
		opt: null,
		searchWidth:"305px",
		inputWidth: "200px",
		nSearch: true,
		readSort: 0,
		searchAuth: true,
		nRead: false,
		nTable: false,
		gotListL:"supShortName",
		gotListV:"supCode"
	},
	legalCodeName: {
		name: "主体法人单位简称",
		type: FORM_TYPE_TEXT,
		addEditType: FORM_TYPE_SELECT,
		searchType: FORM_TYPE_SELECT,
		searchWidth:"305px",
		inputWidth: "200px",
		gotListL:"legalCompSname",
		gotListV:"legalCode",
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},	
	legalCode: {
		name: "主体法人单位简称",
		type: FORM_TYPE_TEXT,
		addEditType: FORM_TYPE_SELECT,
		searchType: FORM_TYPE_SELECT,
		searchWidth:"380px",
		inputWidth: "200px",
		gotListL:"legalCompSname",
		gotListV:"legalCode",
		opt: null,
		nSearch: false,
		readSort: 0,
		nRead: true,
		nTable: true
	},	

	funderCodeName: {
		name: "资金方简称",
		type: FORM_TYPE_TEXT,
		addEditType: FORM_TYPE_SELECT,
		searchType: FORM_TYPE_SELECT,
		searchWidth:"305px",
		inputWidth: "200px",
		rMapper:  true,		
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false,
		gotListL:"funderCodeName",
		gotListV:"funderCode"
	},
	funderCode: {
		name: "资金方简称",
		type: FORM_TYPE_TEXT,
		addEditType: FORM_TYPE_SELECT,
		searchType: FORM_TYPE_SELECT,
		searchWidth:"305px",
		inputWidth: "200px",
		rMapper:  true,		
		opt: null,
		nSearch: false,
		readSort: 0,
		nRead: true,
		nTable: true,
		gotListL:"funderCodeName",
		gotListV:"funderCode"
	},
	mainConCode: {
		name: "业务合同编号",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: false,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	funderConCode: {
		name: "资金合同编号",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: false,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	financeConCode: {
		name: "融资合同编号",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: false,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	financeAmt: {
		name: "融资金额",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	financeDate: {
		name: "融资起日",
		type: FORM_TYPE_TEXT,
		addEditType: FORM_TYPE_DATE_YMD,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	financePeriod: {
		name: "融资账期（天）",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	repayExpcDate: {
		name: "预计还款日",
		addEditType: FORM_TYPE_DATE_YMD,
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	repayType: {
		name: "还款方式",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	mainAuditId: {
		name: "业务审核人员ID",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	mainAuditDatetime: {
		name: "业务审核时间",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	funderAuditId: {
		name: "资金方审核人员ID",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	funderAuditDatetime: {
		name: "资金方审核时间",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	financeConAdd: {
		name: "融资申请合同地址",
		type: FORM_TYPE_IMG,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	fundUsageType: {
		name: "资金用途凭证类型",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	fundUsageAdd: {
		name: "资金用途凭证地址",
		type: FORM_TYPE_IMG,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	funderPayAdd: {
		name: "资金方放款凭证地址",
		type: FORM_TYPE_IMG,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	repayAdd: {
		name: "回款凭证地址",
		type: FORM_TYPE_IMG,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	repayDate: {
		name: "回款日期",
		type: FORM_TYPE_TEXT,
		addEditType: FORM_TYPE_DATE_YMD,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	status: {
		name: "状态",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		nAddOrEdit: true,
		readSort: 0,
		nRead: false,
		nTable: false,
		mapper: "finAplStatus"
	},
	disCostStandard: {
		name: "劳务派遣费用标准",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false,
	},
	auditNote: {
		name: "审核备注",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false,
		mapper: "finAplStatus"
	},
	intRate: {
		name: "融资利率",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false,
	},
	intRatio: {
		name: "融资比率",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false,
	},
	dispatchCorpUnit: {
		name: "被派遣法人单位",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false,
		mapper: "finAplStatus"
	},
	createId: {
		name: "建立人ID",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		nAddOrEdit: true,
		readSort: 0,
		nRead: false,
		nTable: false
	},
	createDatetime: {
		name: "建立日期时间",
		type: FORM_TYPE_TEXT,
		addEditType: FORM_TYPE_DATE_YMD,
		opt: null,
		nSearch: true,
		readSort: 0,
		nAddOrEdit: true,
		nRead: false,
		nTable: false
	},
	modifyId: {
		name: "修改人ID",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nAddOrEdit: true,
		nTable: false
	},
	modifyDatetime: {
		name: "修改日期时间",
		type: FORM_TYPE_TEXT,
		addEditType: FORM_TYPE_DATE_YMD,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: false,
		nTable: false,
		nAddOrEdit: true
	},
	isDelete: {
		name: "是否被删除",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: true,
		nTable: true,
		nAddOrEdit: false,
		nAdd: true,
		nEdit:false
	},
	mainConFunderCode: {
		name: "业务合同的资金方代码（不展示）",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: true,
		nTable: true,
		nAddOrEdit: true,
		nAdd: true,
		nEdit:true
	},
	funderConFunderCode: {
		name: "资金合同的资金方代码（不展示）",
		type: FORM_TYPE_TEXT,
		opt: null,
		nSearch: true,
		readSort: 0,
		nRead: true,
		nTable: true,
		nAddOrEdit: true,
		nAdd: true,
		nEdit:true
	}
};
